/* 本文件由 tools/gen-columns.js 自动生成，不要手改。
 * 改了 public/schema.js（增删题目）后，在 survey 目录执行：  node ../tools/gen-columns.js
 */

export const SURVEY_HEAD = ["编号","提交时间","姓名/队伍","电话"];

export const SURVEY_FIELDS = [
  {"k":"_age","t":"text","label":"年龄"},
  {"k":"_birth","t":"text","label":"出生日期（身份证解析）"},
  {"k":"_ref","t":"text","label":"来源渠道"},
  {"k":"name","t":"text","label":"姓名"},
  {"k":"gender","t":"radio","label":"性别"},
  {"k":"phone","t":"tel","label":"本人手机号"},
  {"k":"wechat","t":"text","label":"微信号 / 备用联系方式"},
  {"k":"idcard","t":"text","label":"身份证号"},
  {"k":"idcard_front","t":"photo","label":"身份证 · 人像面"},
  {"k":"idcard_back","t":"photo","label":"身份证 · 国徽面"},
  {"k":"selfie","t":"photo","label":"本人自拍照（正面半身）"},
  {"k":"live_addr","t":"text","label":"现居住地址"},
  {"k":"is_local","t":"radio","label":"是否在本地长期居住"},
  {"k":"position","t":"checkbox","label":"应聘岗位"},
  {"k":"position_other","t":"text","label":"其他岗位请注明"},
  {"k":"work_years","t":"radio","label":"本行业从业年限"},
  {"k":"emp_type","t":"radio","label":"期望用工形式"},
  {"k":"salary_exp","t":"text","label":"期望薪资"},
  {"k":"salary_cycle","t":"radio","label":"期望结算方式"},
  {"k":"onboard_date","t":"text","label":"可到岗时间"},
  {"k":"source","t":"radio","label":"信息来源"},
  {"k":"edu","t":"radio","label":"最高学历"},
  {"k":"school","t":"text","label":"毕业院校 / 专业"},
  {"k":"certs","t":"checkbox","label":"持有证书（多选，无则留空）"},
  {"k":"drive_type","t":"text","label":"驾驶证准驾车型"},
  {"k":"cert_valid","t":"text","label":"证书有效期至（主要证书）"},
  {"k":"exp_rows.company","t":"rows","from":"exp_rows","col":"company","label":"项目经历 - 公司 / 单位名称"},
  {"k":"exp_rows.project","t":"rows","from":"exp_rows","col":"project","label":"项目经历 - 项目名称及地点"},
  {"k":"exp_rows.content","t":"rows","from":"exp_rows","col":"content","label":"项目经历 - 做了什么（机型 / 规模 / 工艺）"},
  {"k":"exp_rows.period","t":"rows","from":"exp_rows","col":"period","label":"项目经历 - 起止时间"},
  {"k":"exp_rows.role","t":"rows","from":"exp_rows","col":"role","label":"项目经历 - 担任岗位"},
  {"k":"max_project","t":"text","label":"做过的最大项目规模"},
  {"k":"disease","t":"checkbox","label":"是否有以下疾病或身体情况（多选，无则留空）"},
  {"k":"can_high","t":"radio","label":"能否登高作业（2 米及以上）"},
  {"k":"high_type","t":"checkbox","label":"可适应的高空作业形式"},
  {"k":"can_travel","t":"radio","label":"能否接受外地项目出差/驻场"},
  {"k":"can_overtime","t":"radio","label":"能否接受加班/夜间施工"},
  {"k":"smoke_drink","t":"radio","label":"吸烟饮酒情况"},
  {"k":"tools","t":"checkbox","label":"自有工具设备（多选，无则留空）"},
  {"k":"has_car","t":"radio","label":"是否有交通工具"},
  {"k":"emergency_name","t":"text","label":"紧急联系人姓名"},
  {"k":"emergency_rel","t":"text","label":"与本人关系"},
  {"k":"emergency_phone","t":"tel","label":"紧急联系人电话"},
  {"k":"bank_name","t":"text","label":"工资卡开户行"},
  {"k":"bank_account","t":"text","label":"工资卡卡号"},
  {"k":"need_dorm","t":"radio","label":"是否需要提供住宿"},
  {"k":"no_record","t":"radio","label":"是否有违法犯罪记录"},
  {"k":"record_detail","t":"textarea","label":"如有请说明"},
  {"k":"labor_rel","t":"radio","label":"是否与其他单位仍存在未解除的劳动关系"},
  {"k":"remark_entry","t":"textarea","label":"补充说明 / 想让我们了解的内容"},
  {"k":"team_name","t":"text","label":"队伍名称 / 负责人（个人可填本人姓名）"},
  {"k":"contact","t":"tel","label":"联系电话"},
  {"k":"team_size","t":"number","label":"队伍总人数"},
  {"k":"team_struct.role","t":"rows","from":"team_struct","col":"role","label":"人员构成 - 工种/角色（师傅、中工、小工等）"},
  {"k":"team_struct.count","t":"rows","from":"team_struct","col":"count","label":"人员构成 - 人数"},
  {"k":"team_struct.years","t":"rows","from":"team_struct","col":"years","label":"人员构成 - 平均从业年限"},
  {"k":"site_parallel","t":"number","label":"可同时开工的工地数量"},
  {"k":"base_city","t":"text","label":"常驻城市"},
  {"k":"service_area","t":"text","label":"可承接区域"},
  {"k":"has_company","t":"radio","label":"是否有公司主体、能否开票"},
  {"k":"insurance","t":"checkbox","label":"保险情况"},
  {"k":"sys_types","t":"checkbox","label":"可承接的机型 / 系统（多选，必填）"},
  {"k":"main_type","t":"radio","label":"其中最强的一项"},
  {"k":"vrf_brands","t":"checkbox","label":"安装过的品牌（多选）"},
  {"k":"vrf_max_hp","t":"text","label":"单项目最大规模（外机总匹数）"},
  {"k":"vrf_max_idu","t":"number","label":"单项目最多内机台数"},
  {"k":"vrf_pipe","t":"checkbox","label":"铜管施工能力（多选）"},
  {"k":"vrf_pressure","t":"textarea","label":"气密试验做法"},
  {"k":"vrf_vacuum","t":"textarea","label":"真空干燥做法"},
  {"k":"vrf_charge","t":"radio","label":"冷媒追加量如何确定"},
  {"k":"vrf_drain","t":"textarea","label":"冷凝水管道做法"},
  {"k":"vrf_insul","t":"textarea","label":"保温做法"},
  {"k":"vrf_elec","t":"textarea","label":"电气与通讯线做法"},
  {"k":"vrf_debug","t":"checkbox","label":"调试与故障处理能力（多选）"},
  {"k":"vrf_self","t":"scale","label":"多联机综合能力自评"},
  {"k":"w_unit_type","t":"checkbox","label":"安装/配合过的冷源类型（多选）"},
  {"k":"w_capacity","t":"text","label":"做过的最大冷量"},
  {"k":"w_pipe","t":"checkbox","label":"水管施工能力（多选）"},
  {"k":"w_accessory","t":"checkbox","label":"水系统附件安装经验（多选）"},
  {"k":"w_pump","t":"radio","label":"水泵选型与扬程估算能力"},
  {"k":"w_test","t":"textarea","label":"水压试验做法"},
  {"k":"w_tower","t":"textarea","label":"冷却塔安装经验"},
  {"k":"w_terminal","t":"textarea","label":"末端设备安装做法"},
  {"k":"w_insul","t":"textarea","label":"水管与阀门保温做法"},
  {"k":"w_balance","t":"radio","label":"水力平衡调试能力"},
  {"k":"w_antifreeze","t":"textarea","label":"冬季防冻措施"},
  {"k":"w_self","t":"scale","label":"水机系统综合能力自评"},
  {"k":"d_material","t":"checkbox","label":"做过的风管材质（多选）"},
  {"k":"d_thick","t":"text","label":"常用钢板厚度范围"},
  {"k":"d_skill","t":"checkbox","label":"制作安装能力（多选）"},
  {"k":"d_part","t":"checkbox","label":"部件安装经验（多选）"},
  {"k":"d_insul","t":"textarea","label":"风管保温做法"},
  {"k":"d_self","t":"scale","label":"风管专项能力自评"},
  {"k":"f_scope","t":"checkbox","label":"做过的防排烟内容（多选）"},
  {"k":"f_thick","t":"textarea","label":"排烟风管钢板厚度与做法"},
  {"k":"f_valve","t":"textarea","label":"阀门安装要点"},
  {"k":"f_accept","t":"radio","label":"是否熟悉消防验收流程与资料"},
  {"k":"f_cert","t":"checkbox","label":"消防相关证书"},
  {"k":"f_self","t":"scale","label":"防排烟专项能力自评"},
  {"k":"i_brands","t":"checkbox","label":"接触过的品牌"},
  {"k":"i_skill","t":"checkbox","label":"具备能力（多选）"},
  {"k":"i_self","t":"scale","label":"机房空调专项能力自评"},
  {"k":"c_skill","t":"checkbox","label":"具备能力（多选）"},
  {"k":"c_temp","t":"text","label":"做过的库温范围"},
  {"k":"c_self","t":"scale","label":"冷库专项能力自评"},
  {"k":"drawing","t":"checkbox","label":"识图与深化能力"},
  {"k":"weld","t":"checkbox","label":"焊接能力（多选，无则留空）"},
  {"k":"high_work","t":"checkbox","label":"高处与吊装能力（多选）"},
  {"k":"safety","t":"checkbox","label":"安全与规范（多选）"},
  {"k":"docs","t":"checkbox","label":"工程资料能力（多选）"},
  {"k":"equip","t":"checkbox","label":"自有设备（多选）"},
  {"k":"equip_missing","t":"textarea","label":"目前缺什么设备（如需我们提供或租赁）"},
  {"k":"projects.pname","t":"rows","from":"projects","col":"pname","label":"近三年主要业绩（最多 5 个） - 项目名称"},
  {"k":"projects.pscale","t":"rows","from":"projects","col":"pscale","label":"近三年主要业绩（最多 5 个） - 规模（面积/台数）"},
  {"k":"projects.powner","t":"rows","from":"projects","col":"powner","label":"近三年主要业绩（最多 5 个） - 甲方/总包"},
  {"k":"projects.ptime","t":"rows","from":"projects","col":"ptime","label":"近三年主要业绩（最多 5 个） - 时间"},
  {"k":"coop_mode","t":"checkbox","label":"可承接方式"},
  {"k":"quote_mode","t":"checkbox","label":"习惯报价方式"},
  {"k":"max_scale","t":"text","label":"单次可承接的最大规模"},
  {"k":"lead_time","t":"text","label":"最快进场时间"},
  {"k":"warranty","t":"text","label":"可承诺质保期"},
  {"k":"self_level","t":"scale","label":"综合能力自评"},
  {"k":"remark","t":"textarea","label":"补充说明（擅长/不接的活、特殊要求等）"},
  {"k":"declare","t":"radio","label":"本人承诺以上填写内容真实有效，如有虚假愿承担相应责任"},
];

export const EMPLOYEE_HEAD = ["编号","登记时间","姓名","手机号","身份证号","银行卡号","开户行","住址（OCR）","证件风险","照片"];
